// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-metrics-powermax/internal/service/metrictypes (interfaces: PowerMaxClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/powermax_client_mocks.go -package=mocks github.com/dell/csm-metrics-powermax/internal/service/metrictypes PowerMaxClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v2 "github.com/dell/gopowermax/v2"
	v100 "github.com/dell/gopowermax/v2/types/v100"
	gomock "go.uber.org/mock/gomock"
)

// MockPowerMaxClient is a mock of PowerMaxClient interface.
type MockPowerMaxClient struct {
	ctrl     *gomock.Controller
	recorder *MockPowerMaxClientMockRecorder
	isgomock struct{}
}

// MockPowerMaxClientMockRecorder is the mock recorder for MockPowerMaxClient.
type MockPowerMaxClientMockRecorder struct {
	mock *MockPowerMaxClient
}

// NewMockPowerMaxClient creates a new mock instance.
func NewMockPowerMaxClient(ctrl *gomock.Controller) *MockPowerMaxClient {
	mock := &MockPowerMaxClient{ctrl: ctrl}
	mock.recorder = &MockPowerMaxClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPowerMaxClient) EXPECT() *MockPowerMaxClientMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockPowerMaxClient) Authenticate(ctx context.Context, configConnect *v2.ConfigConnect) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, configConnect)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockPowerMaxClientMockRecorder) Authenticate(ctx, configConnect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockPowerMaxClient)(nil).Authenticate), ctx, configConnect)
}

// GetArrayPerfKeys mocks base method.
func (m *MockPowerMaxClient) GetArrayPerfKeys(ctx context.Context) (*v100.ArrayKeysResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArrayPerfKeys", ctx)
	ret0, _ := ret[0].(*v100.ArrayKeysResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArrayPerfKeys indicates an expected call of GetArrayPerfKeys.
func (mr *MockPowerMaxClientMockRecorder) GetArrayPerfKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArrayPerfKeys", reflect.TypeOf((*MockPowerMaxClient)(nil).GetArrayPerfKeys), ctx)
}

// GetStorageGroup mocks base method.
func (m *MockPowerMaxClient) GetStorageGroup(ctx context.Context, symID, storageGroupID string) (*v100.StorageGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageGroup", ctx, symID, storageGroupID)
	ret0, _ := ret[0].(*v100.StorageGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageGroup indicates an expected call of GetStorageGroup.
func (mr *MockPowerMaxClientMockRecorder) GetStorageGroup(ctx, symID, storageGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageGroup", reflect.TypeOf((*MockPowerMaxClient)(nil).GetStorageGroup), ctx, symID, storageGroupID)
}

// GetStorageGroupMetrics mocks base method.
func (m *MockPowerMaxClient) GetStorageGroupMetrics(ctx context.Context, symID, storageGroupID string, metricsQuery []string, firstAvailableTime, lastAvailableTime int64) (*v100.StorageGroupMetricsIterator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageGroupMetrics", ctx, symID, storageGroupID, metricsQuery, firstAvailableTime, lastAvailableTime)
	ret0, _ := ret[0].(*v100.StorageGroupMetricsIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageGroupMetrics indicates an expected call of GetStorageGroupMetrics.
func (mr *MockPowerMaxClientMockRecorder) GetStorageGroupMetrics(ctx, symID, storageGroupID, metricsQuery, firstAvailableTime, lastAvailableTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageGroupMetrics", reflect.TypeOf((*MockPowerMaxClient)(nil).GetStorageGroupMetrics), ctx, symID, storageGroupID, metricsQuery, firstAvailableTime, lastAvailableTime)
}

// GetStorageGroupPerfKeys mocks base method.
func (m *MockPowerMaxClient) GetStorageGroupPerfKeys(ctx context.Context, symID string) (*v100.StorageGroupKeysResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageGroupPerfKeys", ctx, symID)
	ret0, _ := ret[0].(*v100.StorageGroupKeysResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStorageGroupPerfKeys indicates an expected call of GetStorageGroupPerfKeys.
func (mr *MockPowerMaxClientMockRecorder) GetStorageGroupPerfKeys(ctx, symID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageGroupPerfKeys", reflect.TypeOf((*MockPowerMaxClient)(nil).GetStorageGroupPerfKeys), ctx, symID)
}

// GetVolumeByID mocks base method.
func (m *MockPowerMaxClient) GetVolumeByID(ctx context.Context, symID, volumeID string) (*v100.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumeByID", ctx, symID, volumeID)
	ret0, _ := ret[0].(*v100.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolumeByID indicates an expected call of GetVolumeByID.
func (mr *MockPowerMaxClientMockRecorder) GetVolumeByID(ctx, symID, volumeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumeByID", reflect.TypeOf((*MockPowerMaxClient)(nil).GetVolumeByID), ctx, symID, volumeID)
}

// GetVolumesMetrics mocks base method.
func (m *MockPowerMaxClient) GetVolumesMetrics(ctx context.Context, symID, storageGroups string, metricsQuery []string, firstAvailableTime, lastAvailableTime int64) (*v100.VolumeMetricsIterator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumesMetrics", ctx, symID, storageGroups, metricsQuery, firstAvailableTime, lastAvailableTime)
	ret0, _ := ret[0].(*v100.VolumeMetricsIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolumesMetrics indicates an expected call of GetVolumesMetrics.
func (mr *MockPowerMaxClientMockRecorder) GetVolumesMetrics(ctx, symID, storageGroups, metricsQuery, firstAvailableTime, lastAvailableTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumesMetrics", reflect.TypeOf((*MockPowerMaxClient)(nil).GetVolumesMetrics), ctx, symID, storageGroups, metricsQuery, firstAvailableTime, lastAvailableTime)
}
