// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-metrics-powermax/internal/service/metrictypes (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mocks.go -package=mocks github.com/dell/csm-metrics-powermax/internal/service/metrictypes Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	metrictypes "github.com/dell/csm-metrics-powermax/internal/service/metrictypes"
	logrus "github.com/sirupsen/logrus"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ExportCapacityMetrics mocks base method.
func (m *MockService) ExportCapacityMetrics(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExportCapacityMetrics", ctx)
}

// ExportCapacityMetrics indicates an expected call of ExportCapacityMetrics.
func (mr *MockServiceMockRecorder) ExportCapacityMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportCapacityMetrics", reflect.TypeOf((*MockService)(nil).ExportCapacityMetrics), ctx)
}

// ExportPerformanceMetrics mocks base method.
func (m *MockService) ExportPerformanceMetrics(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExportPerformanceMetrics", ctx)
}

// ExportPerformanceMetrics indicates an expected call of ExportPerformanceMetrics.
func (mr *MockServiceMockRecorder) ExportPerformanceMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportPerformanceMetrics", reflect.TypeOf((*MockService)(nil).ExportPerformanceMetrics), ctx)
}

// ExportTopologyMetrics mocks base method.
func (m *MockService) ExportTopologyMetrics(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExportTopologyMetrics", ctx)
}

// ExportTopologyMetrics indicates an expected call of ExportTopologyMetrics.
func (mr *MockServiceMockRecorder) ExportTopologyMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportTopologyMetrics", reflect.TypeOf((*MockService)(nil).ExportTopologyMetrics), ctx)
}

// GetLogger mocks base method.
func (m *MockService) GetLogger() *logrus.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger")
	ret0, _ := ret[0].(*logrus.Logger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockServiceMockRecorder) GetLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockService)(nil).GetLogger))
}

// GetMaxPowerMaxConnections mocks base method.
func (m *MockService) GetMaxPowerMaxConnections() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxPowerMaxConnections")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMaxPowerMaxConnections indicates an expected call of GetMaxPowerMaxConnections.
func (mr *MockServiceMockRecorder) GetMaxPowerMaxConnections() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxPowerMaxConnections", reflect.TypeOf((*MockService)(nil).GetMaxPowerMaxConnections))
}

// GetMetricsRecorder mocks base method.
func (m *MockService) GetMetricsRecorder() metrictypes.MetricsRecorder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricsRecorder")
	ret0, _ := ret[0].(metrictypes.MetricsRecorder)
	return ret0
}

// GetMetricsRecorder indicates an expected call of GetMetricsRecorder.
func (mr *MockServiceMockRecorder) GetMetricsRecorder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricsRecorder", reflect.TypeOf((*MockService)(nil).GetMetricsRecorder))
}

// GetPowerMaxClients mocks base method.
func (m *MockService) GetPowerMaxClients() map[string][]metrictypes.PowerMaxArray {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerMaxClients")
	ret0, _ := ret[0].(map[string][]metrictypes.PowerMaxArray)
	return ret0
}

// GetPowerMaxClients indicates an expected call of GetPowerMaxClients.
func (mr *MockServiceMockRecorder) GetPowerMaxClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerMaxClients", reflect.TypeOf((*MockService)(nil).GetPowerMaxClients))
}

// GetVolumeFinder mocks base method.
func (m *MockService) GetVolumeFinder() metrictypes.VolumeFinder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumeFinder")
	ret0, _ := ret[0].(metrictypes.VolumeFinder)
	return ret0
}

// GetVolumeFinder indicates an expected call of GetVolumeFinder.
func (mr *MockServiceMockRecorder) GetVolumeFinder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumeFinder", reflect.TypeOf((*MockService)(nil).GetVolumeFinder))
}
