// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-metrics-powermax/internal/service/metrictypes (interfaces: MetricsRecorder,MeterCreator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/types_mocks.go -package=mocks github.com/dell/csm-metrics-powermax/internal/service/metrictypes MetricsRecorder,MeterCreator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	metrictypes "github.com/dell/csm-metrics-powermax/internal/service/metrictypes"
	attribute "go.opentelemetry.io/otel/attribute"
	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsRecorder is a mock of MetricsRecorder interface.
type MockMetricsRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRecorderMockRecorder
	isgomock struct{}
}

// MockMetricsRecorderMockRecorder is the mock recorder for MockMetricsRecorder.
type MockMetricsRecorderMockRecorder struct {
	mock *MockMetricsRecorder
}

// NewMockMetricsRecorder creates a new mock instance.
func NewMockMetricsRecorder(ctrl *gomock.Controller) *MockMetricsRecorder {
	mock := &MockMetricsRecorder{ctrl: ctrl}
	mock.recorder = &MockMetricsRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRecorder) EXPECT() *MockMetricsRecorderMockRecorder {
	return m.recorder
}

// RecordNumericMetrics mocks base method.
func (m *MockMetricsRecorder) RecordNumericMetrics(prefix string, labels []attribute.KeyValue, arg2 metrictypes.VolumeCapacityMetricsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordNumericMetrics", prefix, labels, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordNumericMetrics indicates an expected call of RecordNumericMetrics.
func (mr *MockMetricsRecorderMockRecorder) RecordNumericMetrics(prefix, labels, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordNumericMetrics", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordNumericMetrics), prefix, labels, arg2)
}

// RecordStorageGroupPerfMetrics mocks base method.
func (m *MockMetricsRecorder) RecordStorageGroupPerfMetrics(prefix string, arg1 metrictypes.StorageGroupPerfMetricsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordStorageGroupPerfMetrics", prefix, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordStorageGroupPerfMetrics indicates an expected call of RecordStorageGroupPerfMetrics.
func (mr *MockMetricsRecorderMockRecorder) RecordStorageGroupPerfMetrics(prefix, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordStorageGroupPerfMetrics", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordStorageGroupPerfMetrics), prefix, arg1)
}

// RecordTopologyMetrics mocks base method.
func (m *MockMetricsRecorder) RecordTopologyMetrics(ctx context.Context, meta any, arg2 *metrictypes.TopologyMetricsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordTopologyMetrics", ctx, meta, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordTopologyMetrics indicates an expected call of RecordTopologyMetrics.
func (mr *MockMetricsRecorderMockRecorder) RecordTopologyMetrics(ctx, meta, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTopologyMetrics", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordTopologyMetrics), ctx, meta, arg2)
}

// RecordVolPerfMetrics mocks base method.
func (m *MockMetricsRecorder) RecordVolPerfMetrics(prefix string, arg1 metrictypes.VolumePerfMetricsRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordVolPerfMetrics", prefix, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordVolPerfMetrics indicates an expected call of RecordVolPerfMetrics.
func (mr *MockMetricsRecorderMockRecorder) RecordVolPerfMetrics(prefix, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordVolPerfMetrics", reflect.TypeOf((*MockMetricsRecorder)(nil).RecordVolPerfMetrics), prefix, arg1)
}

// MockMeterCreator is a mock of MeterCreator interface.
type MockMeterCreator struct {
	ctrl     *gomock.Controller
	recorder *MockMeterCreatorMockRecorder
	isgomock struct{}
}

// MockMeterCreatorMockRecorder is the mock recorder for MockMeterCreator.
type MockMeterCreatorMockRecorder struct {
	mock *MockMeterCreator
}

// NewMockMeterCreator creates a new mock instance.
func NewMockMeterCreator(ctrl *gomock.Controller) *MockMeterCreator {
	mock := &MockMeterCreator{ctrl: ctrl}
	mock.recorder = &MockMeterCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeterCreator) EXPECT() *MockMeterCreatorMockRecorder {
	return m.recorder
}

// MetricProvider mocks base method.
func (m *MockMeterCreator) MetricProvider() metric.Meter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricProvider")
	ret0, _ := ret[0].(metric.Meter)
	return ret0
}

// MetricProvider indicates an expected call of MetricProvider.
func (mr *MockMeterCreatorMockRecorder) MetricProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricProvider", reflect.TypeOf((*MockMeterCreator)(nil).MetricProvider))
}
