mode: StandAlone
port: 2222
standAloneConfig:
  storageArrays:
    - storageArrayId: "000000000001"
      primaryURL: https://primary.unisphe.re:8443
      proxyCredentialSecrets:
        - proxy-secret-11
        - proxy-secret-12
  managementServers:
    - url: https://primary-1.unisphe.re:8443
      arrayCredentialSecret: primary-1-secret
      certSecret: primary-cert
      skipCertificateValidation: true