mode: StandAlone
port: 2222
standAloneConfig:
  storageArrays:
    - storageArrayId: "000000000001"
      primaryURL:
      proxyCredentialSecrets:
        - proxy-secret-11
        - proxy-secret-12
  managementServers:
    - url: https://primary-1.unisphe.re:8443
      arrayCredentialSecret: primary-1-secret
      certSecret: primary-cert
      skipCertificateValidation: true
    - url: https://backup-1.unisphe.re:8443
      arrayCredentialSecret: backup-1-secret
      skipCertificateValidation: false
    - url: https://primary-2.unisphe.re:8443
      arrayCredentialSecret: primary-2-secret
      skipCertificateValidation: true
    - url: https://backup-2.unisphe.re:8443
      arrayCredentialSecret: backup-2-secret
      skipCertificateValidation: false
